os:
  - 'linux'
sudo: false
language: python
python:
  - '3.5'
  - '3.6'
install:
  - pip install -r ./requirements/ci.txt
  - pip install -e .
script:
  - py.test
after_success:
  - codecov
  - ocular --data-file ".coverage" --config-file ".coveragerc"
