language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
install:
    - pip install -e . --use-mirrors
before_script:
    - pip install coverage coveralls --use-mirrors
script:
    - coverage run `which trial` il2ds_proxy
    - coverage report
after_success:
    - coveralls
