language: python
python:
    - "2.7"
    - "3.3"
    - "pypy"
install:
    - pip install -e . --use-mirrors
before_script:
    #- pip install coverage coveralls --use-mirrors
script:
    #coverage run --source=il2_server_connector setup.py test
after_success:
    #- coveralls
